### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hemanth** [fp-dom/fd-animate#1]
- [ ] Add `isDOM` check.
- [ ] Add other param validations.
- [ ] Figure out a way to test animations of Phantomjs (Test case in place.)
- [ ] API definition in readme.
- [ ] After all of the above, do a major release.
